[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "finance_models"
version = "0.0.1"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "yahoofinancials",
]
