[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "financemodels"
version = "0.0.1"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]
